### ISSUE TITLE
DecoderBlock code wrong?

### ISSUE THREAD

**Issue by Y-H-Joe** [d2l-ai/d2l-en#2057]
Hi guys, firstly, I can't find DecoderBlock in d2l/torch.py (although it exists in book).
Secondly, in forward function, there lies
`if self.training:`
However, no definition of `training` in `__init__` or other part of codes.

**Comment by AnirudhDagar** [comment]
In PyTorch we have two modes while a network is run:
1. `train` mode
1. `eval` mode.


You can take a look at the source [here](https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.train) and find the following.
```python
    def train(self: T, mode: bool = True) -> T:
        r"""Sets the module in training mode.

        This has any effect only on certain modules. See documentations of
        particular modules for details of their behaviors in training/evaluation
        mode, if they are affected, e.g. :class:`Dropout`, :class:`BatchNorm`,
        etc.

        Args:
            mode (bool): whether to set training mode (``True``) or evaluation
                         mode (``False``). Default: ``True``.

        Returns:
            Module: self
        """
        if not isinstance(mode, bool):
            raise ValueError("training mode is expected to be boolean")
        self.training = mode
        for module in self.children():
            module.train(mode)
        return self
```

So internally `self.training` is being toggled to set the mode. Since we are also subclassing from `nn.Module`, we use this variable `self.training` without defining in our init method since it is available in `nn.Module`.

For the DecoderBlock question, we have recently refactored all the code in master with the new API and you may find the DecoderBlock implementation for `Seq2SeqDecoder` [here](http://preview.d2l.ai/d2l-en/master/chapter_recurrent-modern/seq2seq.html#decoder) which again subclasses from `d2l.Decoder` which is actually saved in torch.py with `NotImplemented` returns (see [this](http://preview.d2l.ai/d2l-en/master/chapter_recurrent-modern/encoder-decoder.html#decoder)) since we implement it in `Seq2SeqDecoder`.

I'm closing this for now, hoping I've answered your doubt. Please feel free to reopen and ask/clarify again if something is unclear.
