### ISSUE TITLE
Error in the section GoogleLeNet

### ISSUE THREAD

**Issue by COD1995** [d2l-ai/d2l-en#2253]
When running the notebook using TensorFlow in google Colab, I encountered the following error
![image](https://user-images.githubusercontent.com/50707331/185252203-aa066d3b-e82d-46a8-97c3-e87ee027f1cf.png)
It is in the section of GoogLeNet

**Comment by AnirudhDagar** [comment]
I don't think we can fix this (rather, we probably don't want to fix this). I used tensorflow 2.9.1 on my local machine with python 3.10/3.9/3.8 and all of them work. But for python 3.7 in colab it doesn't. I hope colab can just update soon to python 3.8 at least since that will automatically fix a lot of the issues. This is not a problem with d2l, but a problem in colab.

**Comment by AnirudhDagar** [comment]
Closing since this has been fixed by colab now. Please try again, and feel free to reopen the issue if the problem persists.
