### ISSUE TITLE
Potential issues in 3.3.2. Reading the Dataset

### ISSUE THREAD

**Issue by pmcesky** [d2l-ai/d2l-en#2297]
The scratch implementation of `get_dataloader` in 3.3.2 does not have `__len__` method and would end at StopIteration after one epoch of training. 

So if use the scratch implementation of the `SyntheticRegressionData` in 3.3.1 and 3.3.2 (without running 3.3.3), the training in 3.4.4 would report bugs. One is due to the lack of `__len__` in 3.2.4 `prepare_data` method in `Trainer` class; another is the `fit_epoch` implemented in 3.4.4, which will only do one epoch of training (no matter how big `max_epochs` set in training) due to StopIteration resulting from the generator implementation.

The book should state the above issues explicitly. That may be the reason the book turns to the concise dataloader implementation in 3.3.3.

**Comment by AnirudhDagar** [comment]
Hi @pmcesky, we already mention this in 3.3.3:

> "The new data loader behaves just as the previous one, except that it is more efficient and has some added functionality. For instance, the data loader provided by the framework API  supports the built-in `__len__` method,  so we can query its length, i.e., the number of batches."

I don't understand what you mean by
> "another is the fit_epoch implemented in 3.4.4, which will only do one epoch of training (no matter how big max_epochs set in training) due to StopIteration resulting from the generator implementation."

```python
for epoch in range(10):
    for batch in data.train_dataloader():
        print(batch[0].shape)
        # continue writing your training loop
```
This should work anyway.

The idea is to show the users/readers how a dataloader works under the hood and if someone wants to use it, then they can add the `__len__` magic method themselves, also will need returning a class object instead of a generator in `get_dataloader` scratch.

I'm closing this issue, please feel free to re-open it if I misunderstood something.
